// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SlobSteak.Infrastructure.Persistence;

#nullable disable

namespace SlobSteak.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SlobSteakDbContext))]
    [Migration("20260818195135_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SlobSteak.Domain.Assessments.StakeholderAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Influence")
                        .HasColumnType("integer")
                        .HasColumnName("influence");

                    b.Property<int>("Interest")
                        .HasColumnType("integer")
                        .HasColumnName("interest");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("StakeholderId")
                        .HasColumnType("uuid")
                        .HasColumnName("stakeholder_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_stakeholder_assessments");

                    b.HasIndex("StakeholderId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_stakeholder_assessments_stakeholder_id_role");

                    b.ToTable("stakeholder_assessments", (string)null);
                });

            modelBuilder.Entity("SlobSteak.Domain.Communications.CommunicationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_communication_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_communication_types_name");

                    b.ToTable("communication_types", (string)null);
                });

            modelBuilder.Entity("SlobSteak.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_admin");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SlobSteak.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("SlobSteak.Domain.Projects.ProjectMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_memberships_user_id");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_memberships_project_id_user_id");

                    b.ToTable("project_memberships", (string)null);
                });

            modelBuilder.Entity("SlobSteak.Domain.Stakeholders.Stakeholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LocationDepartment")
                        .HasColumnType("text")
                        .HasColumnName("location_department");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_stakeholders");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_stakeholders_created_by");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_stakeholders_deleted_by");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_stakeholders_project_id");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_stakeholders_updated_by");

                    b.ToTable("stakeholders", (string)null);
                });

            modelBuilder.Entity("SlobSteak.Domain.Stakeholders.StakeholderCommunicationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<Guid>("CommunicationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("communication_type_id");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<Guid>("StakeholderId")
                        .HasColumnType("uuid")
                        .HasColumnName("stakeholder_id");

                    b.HasKey("Id")
                        .HasName("pk_stakeholder_communication_assignments");

                    b.HasIndex("CommunicationTypeId")
                        .HasDatabaseName("ix_stakeholder_communication_assignments_communication_type_id");

                    b.HasIndex("StakeholderId", "CommunicationTypeId")
                        .IsUnique()
                        .HasDatabaseName("ix_stakeholder_communication_assignments_stakeholder_id_commun");

                    b.ToTable("stakeholder_communication_assignments", (string)null);
                });

            modelBuilder.Entity("SlobSteak.Domain.Assessments.StakeholderAssessment", b =>
                {
                    b.HasOne("SlobSteak.Domain.Stakeholders.Stakeholder", null)
                        .WithMany()
                        .HasForeignKey("StakeholderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholder_assessments_stakeholders_stakeholder_id");
                });

            modelBuilder.Entity("SlobSteak.Domain.Projects.ProjectMembership", b =>
                {
                    b.HasOne("SlobSteak.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_memberships_projects_project_id");

                    b.HasOne("SlobSteak.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_memberships_users_user_id");
                });

            modelBuilder.Entity("SlobSteak.Domain.Stakeholders.Stakeholder", b =>
                {
                    b.HasOne("SlobSteak.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholders_users_created_by");

                    b.HasOne("SlobSteak.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stakeholders_users_deleted_by");

                    b.HasOne("SlobSteak.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholders_projects_project_id");

                    b.HasOne("SlobSteak.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholders_users_updated_by");
                });

            modelBuilder.Entity("SlobSteak.Domain.Stakeholders.StakeholderCommunicationAssignment", b =>
                {
                    b.HasOne("SlobSteak.Domain.Communications.CommunicationType", null)
                        .WithMany()
                        .HasForeignKey("CommunicationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholder_communication_assignments_communication_types_c");

                    b.HasOne("SlobSteak.Domain.Stakeholders.Stakeholder", null)
                        .WithMany()
                        .HasForeignKey("StakeholderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholder_communication_assignments_stakeholders_stakehol");
                });
#pragma warning restore 612, 618
        }
    }
}
